name: Zincir API Sync

on:
  schedule:
    - cron: '* * * * *' # Try to run every minute (GitHub best effort)
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run Update Script
        run: node update_api.js

      - name: Commit and Push
        run: |
          git config --global user.name "Zincir-Bot"
          git config --global user.email "bot@zincir.com"
          git add data.json
          git commit -m "Auto Update: $(date)" || echo "No changes to commit"
          git push
